services:
  - type: web
    name: qa-backend-demo
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /api/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: AI__APIKEY
        sync: false
